export default [
    "--media-cache-size=0",
    "--disk-cache-size=0",
    '--headless=new',
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-gpu',
    '--disable-dev-shm-usage',
    '--no-first-run',
    '--no-zygote',
    '--disable-infobars',
    '--mute-audio',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-renderer-backgrounding',
    '--disable-web-security',
    '--autoplay-policy=user-gesture-required',
    '--disable-background-networking',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-component-update',
    '--disable-default-apps',
    '--disable-domain-reliability',
    '--disable-features=AudioServiceOutOfProcess',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-notifications',
    '--disable-offer-store-unmasked-wallet-cards',
    '--disable-popup-blocking',
    '--disable-print-preview',
    '--disable-prompt-on-repost',
    '--disable-speech-api',
    '--disable-sync',
    '--hide-scrollbars',
    '--metrics-recording-only',
    '--no-default-browser-check',
    '--no-pings',
    '--password-store=basic',
    '--use-mock-keychain',
    // //speed up rendering
    // `--enable-thread-composting`,
    // `--enable-zero-copy`,
    // `--enable-checker-imaging`,
    // `--disable-software-rasterizer`,
    // `--num-raster-threads=2`,
    // `--renderer-process-limit=16`,
    // `--enable-main-frame-before-activation`,
];
