version: '3.8'
services:
  render:
    image: 'render'
    volumes:
      - './src:/usr/src/app/src'
      - './tmp:/tmp'
    ports:
      - '8000:80'
    command: 'watch-development'
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - cache:/data
volumes:
  cache:

