name: cd

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: wow
      - run: cp -r wow/* . && rm -rf wow
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build-goerli
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: bb0d3886dd19a135629b19ad98ec61ed
          projectName: open-scrum
          branch: main
          directory: ${{ github.workspace }}/build
