name: render

on:
  push:
    branches:
      - 'master'

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: pull code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '161.35.226.19'
          sync: true
          username: 'root'
          key: ${{ secrets.KEY }}
          script: |
            echo "${{secrets.KEY}}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            git clone git@github.com:FrostF0X/wow-gurt.git || true
            cd ~/wow-gurt/render && git fetch && git reset --hard origin/master
            cd ~/wow-gurt/render && echo "${{secrets.GIT_CRYPT_KEY}}" | base64  -d > ./git-crypt-key
            cd ~/wow-gurt/render && git-crypt unlock ./git-crypt-key
            cd ~/wow-gurt/render && rm ./git-crypt-key
      - name: migrate
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '161.35.226.19'
          sync: true
          username: 'root'
          key: ${{ secrets.KEY }}
          script: |
            cd ~/wow-gurt/render && make prod-migrate
      - name: restart server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '161.35.226.19'
          username: 'root'
          sync: true
          key: ${{ secrets.KEY }}
          script: |
            cp ~/wow-gurt/wow-gurt/render/.deploy/wow-gurt.service /etc/systemd/system/wow-gurt.service
            chown root:root /etc/systemd/system/wow-gurt.service
            chmod 644 /etc/systemd/system/wow-gurt.service
            systemctl daemon-reload
            systemctl restart wow-gurt.service
