name: render

on:
  push:
    branches:
      - 'master'

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: pull code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '159.89.213.104'
          username: 'root'
          key: ${{ secrets.KEY }}
          script: su 'wow-gurt' -c 'cd ~/wow-gurt/render && git pull && npm install'
      - name: restart server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '159.89.213.104'
          username: 'root'
          key: ${{ secrets.KEY }}
          script: systemctl restart wow-gurt.service


