name: render

on:
  push:
    branches:
      - 'master'

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: pull code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '159.89.213.104,157.245.26.106'
          sync: true
          username: 'root'
          key: ${{ secrets.KEY }}
          script: |
            su 'wow-gurt' -c 'cd ~/wow-gurt/render && git pull'
            su 'wow-gurt' -c 'cd ~/wow-gurt/render && echo "${{secrets.GIT_CRYPT_KEY}}" | base64  -d > ./git-crypt-key'
            su 'wow-gurt' -c 'cd ~/wow-gurt/render && git-crypt unlock ./git-crypt-key'
            su 'wow-gurt' -c 'cd ~/wow-gurt/render && rm ./git-crypt-key'
      - name: restart server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '159.89.213.104,157.245.26.106'
          username: 'root'
          sync: true
          key: ${{ secrets.KEY }}
          script: |
            cp /home/wow-gurt/wow-gurt/render/.deploy/wow-gurt.service /etc/systemd/system/wow-gurt.service
            chown root:root /etc/systemd/system/wow-gurt.service
            chmod 644 /etc/systemd/system/wow-gurt.service
            systemctl daemon-reload
            systemctl restart wow-gurt.service


